### ISSUE TITLE
Fatal Error Non Database

### ISSUE THREAD

**Issue by pacong12** [hid0/PPDBsmkw9#1]
> Fatal error: Uncaught mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\PPDBsmkw9\lib\db.class.php:37 Stack trace: #0 C:\xampp\htdocs\PPDBsmkw9\lib\db.class.php(37): mysqli_connect('localhost', 'root', '12', 'db_ppdb') #1 C:\xampp\htdocs\PPDBsmkw9\lib\db.class.php(49): DB_ko->connect() #2 C:\xampp\htdocs\PPDBsmkw9\assets\pages\siswa\login.php(53): DB_ko->query('SELECT * FROM n...') #3 C:\xampp\htdocs\PPDBsmkw9\siswa.php(12): require('C:\\xampp\\htdocs...') #4 {main} thrown in C:\xampp\htdocs\PPDBsmkw9\lib\db.class.php on line 37

untuk solvingnya gimana ya bang?

**Comment by hid0** [comment]
ubah sandi/password mysql nya

kalo make xampp kosongi saja, ane make linux dan sandi phpmyadminnya _"12"_. jadi yaa elu ubah saja sandi sesuai dilaptop elu
klo gasalah edit sandinya did folder **lib/db.class.php**
